# 搞个 ubuntu 环境

version: '3.7'

services:
  ubuntu:
    image: jlvihv/cairo-anaconda-env:0.1.1
    container_name: cairo-python-env
    volumes:
      - ./cairo-project:/cairo-project
    environment:
      - STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
      - STARKNET_NETWORK=alpha-goerli
    working_dir: /cairo-project
    command: starknet-compile erc20.cairo --output erc20.output.json --abi erc20.abi.json